/*
 Cyclic additive group is a group which is generated by adding
 a single element
 For n, generators are all those numbers 'x' < 'n'
 such that adding 'x' single OR multiple times would yield each numbers
 of the set = {0,1.... (n-1)}

NOTES : 
 1.) Total number of generators = phi(n)
     If n is prime , [ result = (n-1) ]
 2.) A number 'x' is generator of 'x' iff 'x' is 
     relatively prime to 'n'  [  gcd(n, x) = 1]
*/

#include<iostream>

using namespace std;

int gcd(int a, int b)
{
  if(a == 0)
    return b;
  return gcd(b%a, a);  
}

void printGenerator(int n)
{
    //'1' is always a generator 
    cout<<"1 ";
    for(int i = 2; i < n; ++i)
       if(gcd(i, n) == 1)
        cout<<i<<" ";
}

int main()
{
    int n = 10;
    printGenerator(n);
    return 0;
}